name: croppy
description: A fully customizable image cropper for Flutter. Mobile-first, but supports Web and Desktop platforms.
version: 1.4.1
homepage: https://github.com/kekland/croppy

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter

  cassowary: ^0.4.3

  plugin_platform_interface: ^2.1.8
  ffi: ^2.1.2

  cupertino_icons: ^1.0.8
  equatable: ^2.0.5
  vector_math: ^2.1.4
  web: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  ffigen: ^12.0.0

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      windows:
        ffiPlugin: true
      web:
